### ISSUE TITLE
Prefers Markbot Issue

### ISSUE THREAD

**Issue by faithebert** [faithebert/prefers-accessibility#1]
Hi there, I ran into this message after doing the assignment for Prefers Accessibility, I have copied and pasted the media query right from the tutorials and triple checked my spelling, I am not sure if there is something I am just not seeing at 8AM on Monday morning or what exactly is happening. Thanks so much!

<img width="498" alt="Screen Shot 2020-11-23 at 8 35 22 AM" src="https://user-images.githubusercontent.com/55109632/99968396-14df6c00-2d67-11eb-8752-18356481ecf1.png">

@hellachella @HannahDelaney

**Comment by HannahDelaney** [comment]
So, weird thing. You may have noticed the comment in your code about how "Markbot is too old to recognize" these media queries. But, the comment tags in there will allow it pass, you just have to put your content inside both.

So, you've started your new queries after the line `/* stylelint-disable media-feature-name-no-unknown */` which is good, but then make sure the line `/* stylelint-enable */` is at the end. Your new queries need to be between them.

**Comment by faithebert** [comment]
Thank you lol *facepalm* I knew it was something silly that I just didn't see. thank you, got it!!
